platform_admin_user:
    resource: |
        alias: sylius.admin_user
        section: admin
        path: users
        templates: PlatformAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: platform_admin_user
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_users_able_to_access_administration_panel
                templates:
                    form: PlatformAdminBundle:AdminUser:_form.html.twig
            index:
                icon: lock
    type: sylius.resource
