admin_platform_role:
    resource: |
        alias: sylius.permission
        section: admin
        path: permissions
        templates: PlatformAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: admin_platform_permission
        form:
            options:
                validation_groups: [platform_admin]
        vars:
            all:
                subheader: sylius.ui.manage_users_able_to_access_administration_panel
                templates:
                    form: PlatformAdminBundle:AdminUser:_form.html.twig
            index:
                icon: lock
    type: sylius.resource
